### ISSUE TITLE
QuizWiz not working

### ISSUE THREAD

**Issue by dallashulsey** [jamesjonesmath/canvancement#14]
Starting on 6-8-2019 The rubric version of Quiz Wiz stopped loading for me in Chrome version 75.0.3770.80 (Official Build) (64-bit) on Windows 10. I tried updating Quizwiz (there wasn't one), restarting my browser, and restarting my computer. It is still not loading in Speedgrader. Tampermonkey is enabled and reports that Quizwiz is on. I do not know what else to try. 🤷‍♂️ Any suggestions, James? 
![2019-06-09_14-47-49](https://user-images.githubusercontent.com/51542405/59164110-e8c62180-8ac5-11e9-8bce-ce5728e93469.png)
![2019-06-01_10-33-51](https://user-images.githubusercontent.com/51542405/59164113-ed8ad580-8ac5-11e9-9158-30a523fd0e42.png)

**Comment by jamesjonesmath** [comment]
The engine to QuizWiz is still working, but the CDN site I'm using it to deliver it has an invalid certificate and so the file isn't getting delivered to your machine to work.

Changing the CDN isn't something I want to do lightly as it will require an update to all of the scripts and may break people's configurations. The certificate issue may remedy itself when the certificate gets fixed. If it continues for a while then I'll research finding a new CDN to deliver the QuizWiz engine.

I've emailed your school address with a different URL that you can use to load it.

**Comment by dallashulsey** [comment]
Thank you, James!

**Comment by jamesjonesmath** [comment]
The CDN certificate issue has been resolved.
