### ISSUE TITLE
QuizWiz Rubrics not working

### ISSUE THREAD

**Issue by teatown** [jamesjonesmath/canvancement#15]
James, Rubrics stopped working some time in the last week (not used since last Sunday). Short answer is still working fine but rubrics, specifically the ability to enter grade at the end of a long essay, no longer appears.  Tried in Firefox (my main browser) and Chrome (just to double check) both are no-go.  Thanks.

**Comment by jamesjonesmath** [comment]
The engine to QuizWiz is still working, but the CDN site I'm using it to deliver it has an invalid certificate and so the file isn't getting delivered to your machine to work.

Changing the CDN isn't something I want to do lightly as it will require an update to all of the scripts and may break people's configurations. The certificate issue may remedy itself when the certificate gets fixed. If it continues for a while then I'll research finding a new CDN to deliver the QuizWiz engine.

I've responded to your message in the Canvas Communtiy with a different URL that you can use to load it.

**Comment by jamesjonesmath** [comment]
The CDN certificate issue has been resolved.
