### ISSUE TITLE
All Courses Sort not working

### ISSUE THREAD

**Issue by exqotile** [jamesjonesmath/canvancement#18]
I've installed the script.    Our all courses url is:
 https://*.instructure.com/courses

Your other scripts do work for us.   I tried running it at home just in case we had something blocked on campus.  Your script simply does nothing.    Did a recent Canvas update break it?

**Comment by jamesjonesmath** [comment]
Thanks for letting me know.

 

Canvas changed when jQuery is loaded on Monday the 21st and it’s not available when the user script runs. I updated some of the scripts that I wrote, but there are about 11 more that I need to update. This is one that I use myself, but very infrequently, so it didn’t get priority on the updates.

**Comment by jamesjonesmath** [comment]
This should be fixed now. Update the user script within Tampermonkey and close the ticket if it works.
