### ISSUE TITLE
Students missing in Canvas Access Report Data

### ISSUE THREAD

**Issue by ozzies-git** [jamesjonesmath/canvancement#27]
Thanks for making this, it's really useful!

I have started using this script only very recently with a combination of up-to-date Firefox & Tampermonkey.

I am able to download the Access Data Report as csv file, however, in the data there are students missing. For example, I have 81 students in a course, but only 57 end up in the report. The students that are missing are active in the course and I can't find something obvious that leaves them out (for example, they are all in the same section in the course).

Am I doing something wrong or is there something I can do to check whether the script comes up with errors or something?

UPDATE: Every time I export the data, the number of students that is included is different (e.g. 51, compared to 57 previously).

Thanks for your time :D

Oscar

**Comment by jamesjonesmath** [comment]
I became aware of the issue through the [Canvas Community](https://community.canvaslms.com/docs/DOC-6061-obtaining-and-using-access-report-data-for-an-entire-course) where there is a description of the problem. For large classes, it's hitting the x-rate-limit-remaining throttle issue. The browsers are now making too many requests at the same time. For smaller classes, it's not an issue.

I am working on a fix. I am rewriting the entire thing to use the Bottleneck JS throttling library and the built in window.fetch method. I am probably 80% done and have it working on my end to the point where it will generate the report. I need to work on the progress bar and the Promises and getting the section name in there (I had to change API calls to one less expensive). There is a new feature coming with it as well :)

Hopefully it will be done today or tomorrow.

**Comment by ozzies-git** [comment]
Ah, I am sorry, I overlooked the 'pages' in the Comments section there! I see that the issue has already been raised there indeed.

Thanks!

**Comment by jamesjonesmath** [comment]
The updated code is now available. Let me know if you have any problems.

**Comment by ozzies-git** [comment]
I did a quest test. The export took (as expected) somewhat longer now and I now have 81 students (= all) in the export file :D.  I don't have time to check content of the exported data now, but it does seem to be working.

Thank you very much, I will let you know if I run into problems later!
