### ISSUE TITLE
PHP HMAC generator does not sort query params correctly

### ISSUE THREAD

**Issue by mbomb007** [jamesjonesmath/canvancement#49]
The HMAC generator in **api.php** has this:

```php
      $parms = explode( '&', $u['query'] );
      ksort( $parms );
      $query = join( '&', $parms );
```

However, `ksort` is the wrong sort function to use here, because the `explode` function returns an array with numeric keys. Sorting by keys will just "sort" the array to be in the order it's already in.

The code should be this:

```php
      $parms = explode('&', $u['query']);
      sort($parms);
      $query = implode('&', $parms);
```

`sort` is used instead of `ksort`, which fixes it.

(`implode` should also be used instead of `join` everywhere). Anyone using PHP's coding standards will see a warning for using `join`, because it's a function alias.)

**Comment by jamesjonesmath** [comment]
Thanks for catching the sort. I've changed the ksort and join functions (there were three of them).
