### ISSUE TITLE
Access Report Data script won't run but did before

### ISSUE THREAD

**Issue by ledelprete** [jamesjonesmath/canvancement#7]
I am having trouble getting this script to run.  It ran beautifully on a different course last November.
Maybe the course is too big?  The current course has 2,400 students  enrolled while the November course only had 250.  The script isn't showing on the dropdown menu under People,

**Comment by ledelprete** [comment]
Thank you so much for your quick response :-)

I truly appreciate your work on this feature because it's going to give us some very useful data for tailoring our program to best meet the needs of our students.

Your observations are correct. I am using Firefox and Grease monkey.  I will try it using Tampermonkey and hope it doesnt time out with 2400 students.

I had already tried line 5 changes and that didn't work...but I will try again w Tampermonkey.

Again, I truly appreciate your help!

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by jamesjonesmath** [comment]
I don't think the issue with the timeout was Tampermonkey as much as Chrome. Tampermonkey works on most of the major browsers, including Firefox. I hope the Tampermonkey / Firefox combo will work for you.

**Comment by ledelprete** [comment]
Oh gosh that is great thank you for explaining that.
I am not very familiar with these types of tools, so I had assumed I had to use Tampermonkey with Chrome. I will let you know how it works out.



Get Outlook for Android<https://aka.ms/ghei36>

**Comment by cjlevesque** [comment]
I've just tried the script with Chrome/Greasemonkey, Chrome/Tampermonkey, and Firefox/Tampermonkey, with a course containing just 11 users. Unfortunately, the progress bar fills to completion, but it never presents the CSV in any of them. As a work around, I'm going to attempt to downgrade Firefox to v54 to see if that will fix the issue.

**Comment by ledelprete** [comment]
I got it to work on my course group with 2400 users. Tampermonkey downloaded then used Firefox as browser ( I think)... it's been a couple days and I tried a couple of different ways.

I haven't had a chance to spot check its accuracy but it did create a file that easily opened in excel.


Get Outlook for Android<https://aka.ms/ghei36>

**Comment by cjlevesque** [comment]
Evidently I'm not firing on all cylinders this week. I was foolishly trying to use the script in a training course that I only had student access in - obviously, I did not have the proper Canvas permissions for it to work. When I tried it in the courses I'm actually teaching (both Firefox and Chrome) it worked perfectly.
